### ISSUE TITLE
Handling filenames with spaces

### ISSUE THREAD

**Issue by stdk** [free-electrons/elixir#23]
Attempting to update a repo that contains files with spaces in their names results in the following output`

```
stdk@stdk:~/dev/elixir$ ./update.py
Found 2 new tags
initial: Traceback (most recent call last):
  File "./update.py", line 138, in <module>
    newBlobs = updateBlobIDs (tag)
  File "./update.py", line 46, in updateBlobIDs
    hash, filename = blob.split (b' ')
ValueError: too many values to unpack (expected 2)
```

Repository that produces such behaviour can be created in the following way:
```
# git init
# echo "int main() { return 0; }" > "Spaces included.c"
# git add "Spaces included.c"
# git commit -m "Initial"
```

**Comment by pokazef** [comment]
Thanks for the patch, I'll merge it right away.
